### ISSUE TITLE
motobug studio dont whats to work

### ISSUE THREAD

**Issue by phithagod24** [coderman64/motobug-engine-designer#13]
C:\Users\Sonic\Downloads\motobug-engine-designer-master\motobug-engine-designer-master>cd C:\Users\Brett\Downloads\motobug-engine-designer-master\motobug-engine-designer-master\

C:\Users\Sonic\Downloads\motobug-engine-designer-master\motobug-engine-designer-master>py main.py
UserWarning: Using SDL2 binaries from pysdl2-dll 2.0.20
Traceback (most recent call last):
  File "C:\Users\Sonic\Downloads\motobug-engine-designer-master\motobug-engine-designer-master\main.py", line 6, in <module>
    from level import level
  File "C:\Users\Sonic\Downloads\motobug-engine-designer-master\motobug-engine-designer-master\level.py", line 3, in <module>
    from items import *
  File "C:\Users\Sonic\Downloads\motobug-engine-designer-master\motobug-engine-designer-master\items.py", line 1, in <module>
    from defusedxml.ElementTree import parse
ModuleNotFoundError: No module named 'defusedxml'

C:\Users\Sonic\Downloads\motobug-engine-designer-master\motobug-engine-designer-master>pause
Press any key to continue . . .
it keeps not working and not working how to fix this???

**Comment by coderman64** [comment]
You are missing a library called "defusedxml"

Try `py -m pip install defusedxml`
